#Reconfigure SOs

- name: Wait 300 seconds, but only start checking after 10 seconds
  wait_for_connection:
    delay: 10
    timeout: 300

- name: Resize Disk size
  shell: |
    growpart /dev/sda 3
    pvresize /dev/sda3
    lvextend -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv
    resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv

- name: Reboot
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 10
    reboot_timeout: 60
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami