# Deploy HAPROXY as Load Balancer

- name: Wait 300 seconds, but only start checking after 15 seconds
  wait_for_connection:
    delay: 15
    timeout: 300

- name: Install HAPROXY
  apt:
    name: haproxy
    state: present

- name: Config file
  copy:
    src: haproxy.cfg
    dest: "/etc/haproxy/haproxy.cfg"
    mode: '0622'

- name: Update hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      10.10.3.15 cluster1k8m1 cluster1k8m1.domain.local
      10.10.3.16 cluster1k8m2 cluster1k8m2.domain.local
      10.10.3.17 cluster1k8m3 cluster1k8m3.domain.local
      192.168.0.85 cluster1k8w1 cluster1k8w1.domain.local
      192.168.0.86 cluster1k8w2 cluster1k8w2.domain.local
      192.168.0.87 cluster1k8w3 cluster1k8w3.domain.local
      192.168.0.89 cluster1k8w4 cluster1k8w4.domain.local
      192.168.0.90 cluster1k8w5 cluster1k8w5.domain.local
      192.168.0.91 cluster1k8w6 cluster1k8w6.domain.local
      192.168.0.94 cluster1k8w7 cluster1k8w7.domain.local
      192.168.0.95 cluster1k8w8 cluster1k8w8.domain.local

- name: Start haproxy
  service:
    name: haproxy
    state: started
    enabled: yes 

- name: Reboot
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 10
    reboot_timeout: 60
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami