# Instala o Kubernetes nos Masters


- name: Wait 300 seconds, but only start checking after 10 seconds
  wait_for_connection:
    delay: 10
    timeout: 300

- name: Disabling swap on hosts…
  shell: swapoff -a

- name: Delete swap
  shell: sed -i -e 's/\/swap.img/\# \/swap.img/g' /etc/fstab

- name: Update hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      10.10.3.14 cluster1k8lb cluster1k8lb.domain.local
      10.10.3.15 cluster1k8m1 cluster1k8m1.domain.local
      10.10.3.16 cluster1k8m2 cluster1k8m2.domain.local
      10.10.3.17 cluster1k8m3 cluster1k8m3.domain.local
      192.168.0.85 cluster1k8w1 cluster1k8w1.domain.local
      192.168.0.86 cluster1k8w2 cluster1k8w2.domain.local
      192.168.0.87 cluster1k8w3 cluster1k8w3.domain.local
      192.168.0.89 cluster1k8w4 cluster1k8w4.domain.local
      192.168.0.90 cluster1k8w5 cluster1k8w5.domain.local
      192.168.0.91 cluster1k8w6 cluster1k8w6.domain.local
      192.168.0.94 cluster1k8w7 cluster1k8w7.domain.local
      192.168.0.95 cluster1k8w8 cluster1k8w8.domain.local
      ipv6:85 cluster1k8w1 cluster1k8w1.domain.local
      ipv6:86 cluster1k8w2 cluster1k8w2.domain.local
      ipv6:87 cluster1k8w3 cluster1k8w3.domain.local
      ipv6:89 cluster1k8w4 cluster1k8w4.domain.local
      ipv6:90 cluster1k8w5 cluster1k8w5.domain.local
      ipv6:91 cluster1k8w6 cluster1k8w6.domain.local
      ipv6:94 cluster1k8w7 cluster1k8w7.domain.local
      ipv6:95 cluster1k8w8 cluster1k8w8.domain.local

- name: Kubernetes modules
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    create: yes
    block: |
      br_netfilter
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      nf_conntrack_ipv4
      ip_vs
      overlay

- name: Kubernetes blacklist modules
  blockinfile:
    path: /etc/modprobe.d/kubernetes-blacklist.conf
    create: yes
    block: |
      # DCCP is unlikely to be needed, has had multiple serious
      # vulnerabilities, and is not well-maintained.
      blacklist dccp
      #
      # SCTP is not used in most Kubernetes clusters, and has also had
      # vulnerabilities in the past.
      blacklist sctp

- name: Installing Required packages
  package: 
    name: "{{ item }}"
    state: present
  with_items: "{{ pkgs }}"

- name: Reiniciar para aplicar alterações
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 60
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: Get docker gpg key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee -a /etc/apt/sources.list.d/docker.list > /dev/null
    mkdir /etc/docker

- name: Update apt cache
  apt:
    update_cache: yes

- name: Installing Docker
  package: 
    name: "{{ item }}"
    state: present
  with_items: "{{ dck }}"

- name: Create docker daemon file
  blockinfile:
    path: /etc/docker/daemon.json
    create: yes
    marker: ""
    block: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

- name: Create docker service
  shell: |
    mkdir -p /etc/systemd/system/docker.service.d
    systemctl daemon-reload

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes 


## Installing kubernetes

- name: Kubernetes modules
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    create: yes
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Enable netfilter sysctl
  shell: sysctl --system

- name: Get google cloud gpg key
  shell: |
    sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Installing Kubernetes
  package: 
    name: "{{ item }}"
    state: present
  with_items: "{{ k8s }}"

- name: Holding packages
  shell: apt-mark hold kubelet kubeadm kubectl docker-ce docker-ce-cli containerd.io

- name: Pulling images required for setting up a Kubernetes cluster
  shell: kubeadm config images pull

