---
##########################################################################
### Kubernetes highly available cluster by Ansible playbook            ###
###                                                                    ###
### Author: Renato Moreira                                             ###
### Date: 04/02/2022                                                   ###
##########################################################################

#Reconfigure Ubuntu parameters after clone template
- name: Adjust SOs
  hosts: All_servers
  remote_user: root
#  become: yes
  gather_facts: no

  pre_tasks:
    - name: Ensure PIP exists.
      apt:
        name:
          - python3-pip
        state: present

  roles:
  - ubuntu_adjust

# Create HAPROXY loadbalance.
- name: Deploy LB haproxy
  hosts: Load
  remote_user: root
#  become: yes
  gather_facts: no

  roles:
  - install_lb

#Install docker/kubernetes
- name: Deploy apps
  hosts: Kubernetes:children
  remote_user: root
#  become: yes
  gather_facts: no

  roles:
  - install_kubernetes


#Create cluster
- name: Create k8s cluster
  hosts: 10.10.3.15
  remote_user: root
#  become: yes
  gather_facts: no

  roles:
  - configure_master

# Join additional masters
- name: Join k8s masters
  serial: 1
  hosts: 
    10.10.3.16
    10.10.3.17
  remote_user: root
#  become: yes
  gather_facts: no

  roles:
  - join_master

# Join workers
- name: Join k8s workers
  hosts: Workers
  remote_user: root
  serial: 3
#  become: yes
  gather_facts: no

  roles:
  - join_worker


# Install additional tools
- name: Aditional tools
  hosts: 10.30.3.15
  remote_user: root
#  become: yes
  gather_facts: no

  roles:
  - install_k_tools
