apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns
spec:
  acme:
    email: contact@domain ## letsencrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencript-staging-dns 
    solvers:
    - dns01: 
        cnameStrategy: Follow 
        rfc2136:
          nameserver: ns1.domain.local:53 #bind server
          tsigKeyName: bindKey. #key in bind server
          tsigAlgorithm: HMACSHA512
          tsigSecretSecretRef:
            name: tsig-secret
            key: tsig-secret-key